path_abundances <- ''
path_metadata <- ''
path_bacteria <- ''

path_temperatures <- ''
path_bacteria_species_counts <- ''
path_taxonomy_table <- ''
path_adjacencies <- ''
path_species <- ''
path_correlations <- ''
path_taxonomy_modularity <- ''
path_globalThreshold_metrics <- ''
path_localThresholdData <- ''
path_localThreshold_metrics <- ''
path_communities <- ''